# Generated by Django 5.2 on 2025-05-07 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorder',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.carconfiguration'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('in_progress', 'В процессе')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='carorder',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('in_progress', 'В процессе')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('in_progress', 'В процессе')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('in_progress', 'В процессе')], default='pending', max_length=50),
        ),
    ]
