# Generated by Django 5.2 on 2025-04-27 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_salesemployee_salecontract_sales_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carorder',
            old_name='created_at',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='carorder',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='carorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carorder',
            name='full_name',
        ),
        migrations.AddField(
            model_name='carorder',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('delivered', 'Доставлен')], default='pending', max_length=50),
        ),
    ]
