# Generated by Django 5.2 on 2025-04-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_salesemployee_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('view_all_orders', 'Can view all car orders')]},
        ),
    ]
